const Types ={
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: " LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_ERROR: "REGISTER_ERROR",
    LOGOUT: "LOGOUT",
    REFRESH_REQUEST: "REFRESH_REQUEST",
    REFRESH_SUCCESS: "REFRESH_SUCCESS",
    REFRESH_ERROR: "REFRESH_ERROR"
}

export default Types;